version: 1
services:
  web:
    type: web
    name: render-web-service
    env: node
    buildCommand: npm install
    startCommand: node ./render-web-service/src/server.js
    envVars:
      NODE_ENV: production
